name = "GraphDatasets"
uuid = "bf13de61-383b-4610-8d2c-e75fac0df62b"
authors = ["Simon Schoelly <sischoel@gmail.com> and contributors"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
SimpleValueGraphs = "b43c691f-cac2-5415-8122-396fe16a49fc"

[compat]
julia = "1.5"
SimpleValueGraphs = "0.3.1"
DataDeps = "0.7.7"
CSV = "0.8.3"
LightGraphs = "1.3.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
